### ISSUE TITLE
game not working after first time the game wins

### ISSUE THREAD

**Issue by arunimgarg** [thearubik/NumberWizardConsoleGame#1]
Observed behavior:
after the game reaches it's outcome (win; correctly guessing the number thought by the player) for the first time, it gets buggy right after that stage. 
Pushing up and down arrows don't bring the results anymore, although before winning for the first time pushing the arrows would do exactly what they are meant for.

Expected behavior:
after the game wins for the first time, it is expected to work just like how it works for the first time you play the game. Up arrow should take the number to 750 ((min+max)/2) and down arrow to 250 etc...

Steps to reproduce:
Play the game and reach the stage where the game wins for the first time. When the game restarts, try pressing up and down arrows, it will be then the game will start the bug out.

Steps already taken:
I looked at the script to find any anomalies but i couldn't find anything wrong. No actual steps taken to fix the code just yet.

**Comment by gaviral** [comment]
Great issue created. Very thorough and informative! 

Things to note:
1. you said it got buggy at a certain stage but did not state what exactly that bug is.
2. You should always try to add images in issues whenever possible

Following would make life easier:
![image](https://user-images.githubusercontent.com/12901566/35701132-ed4697f4-0749-11e8-8f60-087e1bbc0789.png)
The circled log was printed after pressing the up arrow key twice.

Another interesting thing to note is that these comments follow the .md format.

**Comment by gaviral** [comment]
![image](https://user-images.githubusercontent.com/12901566/35701699-b19d1488-074b-11e8-8ca7-1e9ca1bafd64.png)

Because the collapse button was on, after winning when I pressed the up arrow the first time the message 'Is the number higher or lower than 750?' got collapsed (as seen in the circled number '2'). and then after pressing up arrow key again showed the message 'Is the number higher or lower than 875?' was shown because it had not occurred in the log before. 

It seems to be a bug by unity since only continuous same log messages must be collapsed.
